FROM python:3.9.18-slim

RUN pip install pipenv
RUN pip install gunicorn

WORKDIR /app                                                                

COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --deploy --system

COPY ["predict.py", "model.bin", "scaler.bin", "dv.bin", "./"]